# Generated by Django 4.2.3 on 2023-07-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("priority", models.IntegerField(default=1)),
                ("due_date", models.DateField(auto_now=True, verbose_name="Updated")),
                ("completed", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=50)),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent on the task (in minutes)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("tag", models.CharField(max_length=50)),
            ],
        ),
    ]
