# Generated by Django 4.2.3 on 2023-07-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="time_spent",
        ),
    ]
